In [2]:
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(m)

for row in m:
    print(row)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [5]:
i = int(input("Enter i: "))
j = int(input("Enter j: "))
print('m[{}][{}] = {}'.format(i, j, m[i][j]))

m[1][2] = 6


In [7]:
last_rows = m[1:]
print(last_rows)
for row in last_rows:
    print(row)

[[4, 5, 6], [7, 8, 9]]
[4, 5, 6]
[7, 8, 9]


In [8]:
m = [[1], [2, 3], [4, 5, 6]]
for row in m:
    print(row)

[1]
[2, 3]
[4, 5, 6]


In [11]:
import random as rd
m = [list(rd.sample(range(10, 100), 5)),
     list(rd.sample(range(10, 100), 5)),
     list(rd.sample(range(10, 100), 5)),
     list(rd.sample(range(10, 100), 5)),
     list(rd.sample(range(10, 100), 5))]
for row in m:
    print(row)

[99, 90, 76, 75, 27]
[75, 78, 21, 80, 23]
[10, 74, 18, 83, 53]
[31, 57, 52, 92, 75]
[91, 90, 34, 62, 29]


In [12]:
for row in m[1:-1]:
    print(row)

[75, 78, 21, 80, 23]
[10, 74, 18, 83, 53]
[31, 57, 52, 92, 75]


In [13]:
for row in m[-2:]:
    print(row)

[31, 57, 52, 92, 75]
[91, 90, 34, 62, 29]


In [18]:
n = int(input("Enter n: "))
print('Max of row[{}]: {}'.format(n, max(m[n])))
print('Min of row[{}]: {}'.format(n, min(m[n])))
print('Sum of row[{}]: {}'.format(n, sum(m[n])))
print('Sorted row[{}]: {}'.format(n, sorted(m[n])))

Max of row[2]: 83
Min of row[2]: 10
Sum of row[2]: 238
Sorted row[2]: [10, 18, 53, 74, 83]


In [20]:
import numpy as np
# create array from list
a = [1, 2, 3, 4]
arr = np.array(a)
print(a, arr, type(arr), sep='\n')

[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>


In [21]:
print(arr[2])
print(arr[2:])

3
[3 4]


In [ ]:
a = [1, 'hello', 3, 4.0]
arr = np.array(a)
print(arr)

In [24]:
names = ['John', 'Paul', 'Mike', 'George']
names[0] = 'John Smith'
print(names)

['John Smith', 'Paul', 'Mike', 'George']


In [25]:
a = list(range(10))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [26]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
a = np.arange(10, 20)
print(a)
b = np.arange(10, 100, 5)
print(b)

[10 11 12 13 14 15 16 17 18 19]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [34]:
a = np.linspace(0, 10, 6, dtype=int)
print(a)

[ 0  2  4  6  8 10]


In [35]:
a = np.arange(0, 10, 0.5)
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [38]:
# create 20 numbers from 0 to 1
a = np.linspace(0, 1, 20, endpoint=False)
print(a)
# create numbers from 0 to 1, step 0.05
b = np.arange(0, 1, 0.05)
print(b)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]
[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [42]:
a = np.logspace(0, 10, 11, base=2, dtype=int)
for n in a:
    print(n)

1
2
4
8
16
32
64
128
256
512
1024


In [43]:
all_zeros = np.zeros(10)
print(all_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [44]:
all_ones = np.ones(10, dtype=int)
print(all_ones)

[1 1 1 1 1 1 1 1 1 1]


In [45]:
# array of random numbers
a = np.random.randint(0, 100, 10)
print(a)

[71 16 66 22 43  3 75  8 19 73]


In [46]:
# Vectorized operations on arrays
b = a + all_ones
print(b)

[72 17 67 23 44  4 76  9 20 74]


In [47]:
c = a + 1
print(c)

[72 17 67 23 44  4 76  9 20 74]
