In [1]:
import numpy as np
# random of 20 integers between 0 and 99
a = np.random.randint(0, 100, 20)
print(a)

[23 93 56 86 19 84 88 43  0 17 75 94 95 60 39 53 67 40 66 70]


In [2]:
for i in range(len(a)):
    if a[i] % 2 == 0:
        print(a[i], end=' ')

56 86 84 88 0 94 60 40 66 70 

In [3]:
# find evens in a using boolean indexing
evens = a[a % 2 == 0]
print(evens)

[56 86 84 88  0 94 60 40 66 70]


In [4]:
b = a % 2 == 0
print(a, b, sep='\n')

[23 93 56 86 19 84 88 43  0 17 75 94 95 60 39 53 67 40 66 70]
[False False  True  True False  True  True False  True False False  True
 False  True False False False  True  True  True]


In [5]:
evens = a[b]
print(evens)

[56 86 84 88  0 94 60 40 66 70]


In [7]:
evens = a[a%2==0]
# find odds numbers
odds = a[a%2!=0]
print(odds)
# find numbers that greater than 50
bigs = a[a>50]
print(bigs)
# find numbers that ends with 3
end3 = a[a%10==3]
print(end3)

[23 93 19 43 17 75 95 39 53 67]
[93 56 86 84 88 75 94 95 60 53 67 66 70]
[23 93 43 53]


In [11]:
a = np.random.randint(-99, 100, 20)
print(a)
# find negative numbers
negatives = a[a<0]
print(negatives)
# find positive numbers
positives = a[a>0]
print(positives)
# find numbers that ends with 8
end8 = a[np.abs(a)%10==8]
print(end8)

[-32  20 -98  56  60 -25  14  90   3 -76  72  38 -92  47   8 -74 -49 -90
  39  57]
[-32 -98 -25 -76 -92 -74 -49 -90]
[20 56 60 14 90  3 72 38 47  8 39 57]
[-98  38   8]


In [12]:
a = np.random.randint(-99, 100, 20)
b = np.random.randint(-99, 100, 20)
# find numbers in a that are sign corresponding to numbers in b
c = a[a*b>0]
print(a, b, c, sep='\n')

[-10  -4 -15 -92  -5  64  92  15  15  26  40  12  34 -30  45   9 -20 -58
  24  51]
[-78  57  18  85  27 -89 -52  24 -30 -31 -51  12 -56  39 -68  63  75  65
  24 -10]
[-10  15  12   9  24]


In [15]:
# convert negative numbers to positive
a = np.random.randint(-99, 100, 20)
print(a)
a[a<0] *= -1
print(a)

[-35  17  48  23 -42  73  27  35 -66  33 -19  43 -15  86  60  17 -30   9
 -83 -92]
[35 17 48 23 42 73 27 35 66 33 19 43 15 86 60 17 30  9 83 92]


In [20]:
names = np.array(['Bob Dylan', 'Joe Aggrington', 'Will Smith', '', 'Micheal Jackson', '', ''])
print(names)

['Bob Dylan' 'Joe Aggrington' 'Will Smith' '' 'Micheal Jackson' '' '']


In [21]:
# change empty names to default name 'John Doe'
names[names == ''] = 'John Doe'
print(names)

['Bob Dylan' 'Joe Aggrington' 'Will Smith' 'John Doe' 'Micheal Jackson'
 'John Doe' 'John Doe']


In [24]:
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.]) 
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2])
v0 = (y[1] - y[0]) / (t[1] - t[0])
v1 = (y[2] - y[1]) / (t[2] - t[1])
print(v0, v1)
for i in range(1, len(y)):
    v = (y[i] - y[i-1]) / (t[i] - t[i-1])
    print(v, end=' ')

2.653061224489796 7.254901960784314
2.653061224489796 7.254901960784314 11.8 13.793103448275858 20.851063829787247 17.384615384615376 

In [25]:
v = (y[1:] - y[:-1]) / (t[1:] - t[:-1])
print(v)

[ 2.65306122  7.25490196 11.8        13.79310345 20.85106383 17.38461538]
