In [1]:
a = [[1],
     [2, 3],
     [4, 5, 6]]
print(a)

[[1], [2, 3], [4, 5, 6]]


In [3]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a, a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a, a.shape)
b = np.reshape(a, (3, 2))
c = np.reshape(a, (2, 3))
d = np.reshape(a, (1, 6))
e = np.reshape(a, (6, 1))
print(b, b.shape, c, c.shape, d, d.shape, e, e.shape, sep='\n')

[1 2 3 4 5 6] (6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [ ]:
f = np.reshape(a, (3, 3)) # error

In [10]:
# create matrix 5x5 of random integers
a = np.random.randint(10, 100, (5, 5))
print(a)
print(a[2, 3], a[2, -2], a[-3, 3], a[-3, -2], sep='\n')

[[96 98 29 79 88]
 [50 75 13 10 56]
 [45 34 39 17 84]
 [50 27 52 64 53]
 [47 56 87 66 46]]
17
17
17
17


In [18]:
print(a[3, 2:4])
print(a[1:4, 3])
print(a[1:4, 2:4])
print(a[:, 3])
print(a[::2, :])
print(a[::2, ::2])

[52 64]
[10 17 64]
[[13 10]
 [39 17]
 [52 64]]
[79 10 17 64 66]
[[96 98 29 79 88]
 [45 34 39 17 84]
 [47 56 87 66 46]]
[[96 29 88]
 [45 39 84]
 [47 87 46]]


In [21]:
a = np.ones((3, 3), dtype=int)
print(a)
a[1] = 0
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [0 0 0]
 [1 1 1]]


In [22]:
a = np.ones((8, 8), dtype=int)
a[1:7, 1:7] = 0
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [24]:
a = np.ones((8, 8), dtype=int)
a[::2, ::2] = 0
a[1::2, 1::2] = 0
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
a = np.zeros((8, 8), dtype=int)
a[::2, 1::2] = 1
a[1::2,::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
a = np.random.randint(10, 100, (8, 8))
print(a)
a[a%3!=0] *= -1
print(a)

[[46 89 90 41 64 66 89 53]
 [69 35 70 74 90 14 72 90]
 [94 41 90 17 59 95 21 83]
 [99 89 91 89 66 29 50 27]
 [98 92 45 78 91 18 10 81]
 [80 62 37 95 45 69 91 17]
 [44 35 46 47 11 91 21 34]
 [59 14 11 94 97 72 35 95]]
[[-46 -89  90 -41 -64  66 -89 -53]
 [ 69 -35 -70 -74  90 -14  72  90]
 [-94 -41  90 -17 -59 -95  21 -83]
 [ 99 -89 -91 -89  66 -29 -50  27]
 [-98 -92  45  78 -91  18 -10  81]
 [-80 -62 -37 -95  45  69 -91 -17]
 [-44 -35 -46 -47 -11 -91  21 -34]
 [-59 -14 -11 -94 -97  72 -35 -95]]


In [31]:
q2 = a[:4, 4:]
print('Size: ', q2.size)
print('Shape: ', q2.shape)
print('Mean: ', q2.mean())
print('Standard deviation: ', np.std(q2))
print(type(q2))

Size:  16
Shape:  (4, 4)
Mean:  -6.5
Standard deviation:  65.35862605655049
<class 'numpy.ndarray'>


In [32]:
rooms = {'Emma': 309, 'John': 204, 'Paul': 105, 'Mary': 105}
print(rooms)

{'Emma': 309, 'John': 204, 'Paul': 105, 'Mary': 105}


In [33]:
print(rooms['Emma'])

309


In [34]:
rooms['Peter'] = 400 # insert item to dictionary
print(rooms)

{'Emma': 309, 'John': 204, 'Paul': 105, 'Mary': 105, 'Peter': 400}


In [35]:
rooms['Peter'] = 500 # update item in dictionary
print(rooms)

{'Emma': 309, 'John': 204, 'Paul': 105, 'Mary': 105, 'Peter': 500}


In [36]:
# Enter new guest
guest = input('Enter guest name: ')
room_no = int(input('Enter room number: '))
rooms[guest] = room_no

In [40]:
print(rooms)

{'Emma': 309, 'John': 204, 'Paul': 105, 'Mary': 105, 'Peter': 500, 'Kim': 120}


In [39]:
# Change room for a guest
guest = input('Enter guest name: ')
# check if guest is in the dictionary
if guest in rooms:
    room_no = int(input('Enter new room number: '))
    rooms[guest] = room_no
else:
    print('Guest not found')

In [42]:
# Guest check out
guest = input('Enter guest name: ')
if guest in rooms:
    room_no = rooms.pop(guest)
    print('Guest', guest, 'check out')
    print('Room {} is available'.format(room_no))
else:
    print('Guest not found')

Guest Emma check out
Room 309 is available


In [43]:
print(rooms)

{'John': 204, 'Paul': 105, 'Mary': 105, 'Peter': 500, 'Kim': 120}


In [47]:
print(list(rooms.keys()))
print(rooms.values())
print(rooms.get('John'))

['John', 'Paul', 'Mary', 'Peter', 'Kim']
dict_values([204, 105, 105, 500, 120])
204
