In [1]:
def myfunc(a, b, c=10, d='hello'):
    print(a, b, c, d)

In [2]:
myfunc(1, 2)

1 2 10 hello


In [3]:
myfunc(1, 2, 'hello')

1 2 hello hello


In [4]:
myfunc(1, 2, d='hello')

1 2 10 hello


In [5]:
myfunc(1, 2, d='hello', c=10)

1 2 10 hello


In [7]:
myfunc(1, 2, 'hello', 10)

1 2 hello 10


In [21]:
def mysum(*items):
    print(items, type(items))
    total = 0
    for i in items:
        total += i
    return total

In [3]:
def mysum_list(items):
    total = 0
    for i in items:
        total += i
    return total

In [22]:
import numpy as np
print(mysum(np.array([1, 2, 3]), np.array([4, 5, 6]), 9))
print(mysum_list([4, 5, 6]))

(array([1, 2, 3]), array([4, 5, 6]), 9) <class 'tuple'>
[14 16 18]
15


In [19]:
def my_max(*items):
    if len(items) == 0:
        return None
    m = items[0]
    for i in items:
        if i > m:
            m = i
    return m

In [20]:
print(my_max(4, 5))
print(my_max(4, 45, 19))
print(my_max())

5
45
None


In [25]:
def min_max(items):
    mi = min(items)
    ma = max(items)
    return mi, ma

In [27]:
numbers = np.random.randint(1, 100, 10)
print(numbers)
a, b = min_max(numbers)
print('Min =', a, 'Max =', b)

[ 6 25 64 73 83 53 19 49 62 15]
Min = 6 Max = 83


In [29]:
ab = min_max(numbers)
print('Min =', ab[0], 'Max =', ab[1])

Min = 6 Max = 83


In [35]:
def less_than(a, b):
    return a < b
def greater_than(a, b):
    return a > b
def my_min_max(items, compare=less_than):
    m = items[0]
    for i in items:
        if compare(i, m):
            m = i
    return m

In [36]:
print(my_min_max([4, 5, 8, 2], compare=greater_than))

8


In [37]:
print(numbers)

[ 6 25 64 73 83 53 19 49 62 15]


In [39]:
def less_than_digit(a, b):
    return a % 10 < b % 10
def greater_than_digit(a, b):
    return a % 10 > b % 10
print(my_min_max(numbers, compare=less_than_digit))
print(my_min_max(numbers, compare=greater_than_digit))

62
19


In [ ]:
names = ['John Murray', 'Mike Smith', 'Sara Henderson', 'Laura Amstrong', 'Zack Swzenks']
# Find longest name
# Find shortest name
# Find name that has least vowels
# Find name that has most vowels