In [1]:
def myfunc(a, b, c=10, d='hello'):
    print(a, b, c, d)

In [2]:
myfunc(1, 2)

1 2 10 hello


In [3]:
myfunc(1, 2, 'hello')

1 2 hello hello


In [4]:
myfunc(1, 2, d='hello')

1 2 10 hello


In [5]:
myfunc(1, 2, d='hello', c=10)

1 2 10 hello


In [7]:
myfunc(1, 2, 'hello', 10)

1 2 hello 10


In [21]:
def mysum(*items):
    print(items, type(items))
    total = 0
    for i in items:
        total += i
    return total

In [3]:
def mysum_list(items):
    total = 0
    for i in items:
        total += i
    return total

In [22]:
import numpy as np
print(mysum(np.array([1, 2, 3]), np.array([4, 5, 6]), 9))
print(mysum_list([4, 5, 6]))

(array([1, 2, 3]), array([4, 5, 6]), 9) <class 'tuple'>
[14 16 18]
15


In [19]:
def my_max(*items):
    if len(items) == 0:
        return None
    m = items[0]
    for i in items:
        if i > m:
            m = i
    return m

In [20]:
print(my_max(4, 5))
print(my_max(4, 45, 19))
print(my_max())

5
45
None


In [25]:
def min_max(items):
    mi = min(items)
    ma = max(items)
    return mi, ma

In [27]:
numbers = np.random.randint(1, 100, 10)
print(numbers)
a, b = min_max(numbers)
print('Min =', a, 'Max =', b)

[ 6 25 64 73 83 53 19 49 62 15]
Min = 6 Max = 83


In [29]:
ab = min_max(numbers)
print('Min =', ab[0], 'Max =', ab[1])

Min = 6 Max = 83


In [35]:
def less_than(a, b):
    return a < b
def greater_than(a, b):
    return a > b
def my_min_max(items, compare=less_than):
    m = items[0]
    for i in items:
        if compare(i, m):
            m = i
    return m

In [36]:
print(my_min_max([4, 5, 8, 2], compare=greater_than))

8


In [37]:
print(numbers)

[ 6 25 64 73 83 53 19 49 62 15]


In [39]:
def less_than_digit(a, b):
    return a % 10 < b % 10
def greater_than_digit(a, b):
    return a % 10 > b % 10
print(my_min_max(numbers, compare=less_than_digit))
print(my_min_max(numbers, compare=greater_than_digit))

62
19


In [42]:
names = ['John Murray', 'Mike Smith', 'Sara Henderson', 'Laurent Amstrong', 'Zack Swzenks']
def less_than_length(a, b):
    return len(a) < len(b)
print(my_min_max(names, compare=less_than_length))
def greater_than_length(a, b):
    return len(a) > len(b)
print(my_min_max(names, compare=greater_than_length))

def count_vowels(s):
    n_vowels = 0
    vowels = 'aeiou'
    for c in s:
        n_vowels += 1 if c in vowels else 0
    return n_vowels

def less_than_vowels(a, b):
    return count_vowels(a) < count_vowels(b)

# Find name that has least 
print(my_min_max(names, compare=less_than_vowels))
# Find name that has most vowels
def greater_than_vowels(a, b):
    return count_vowels(a) > count_vowels(b)
print(my_min_max(names, compare=greater_than_vowels))

Mike Smith
Laurent Amstrong
Zack Swzenks
Sara Henderson


In [48]:
def same(x):
    return x
def my_min(items, key=same):
    m = items[0]
    for i in items:
        if key(i) < key(m):
            m = i
    return m

In [49]:
print(numbers)
print(my_min(numbers))

[ 6 25 64 73 83 53 19 49 62 15]
6


In [51]:
def digit(x):
    return x % 10

print(my_min(numbers, key=digit))
print(names)
print('Shortest name:', my_min(names, key=len))

62
['John Murray', 'Mike Smith', 'Sara Henderson', 'Laurent Amstrong', 'Zack Swzenks']
Shortest name: Mike Smith


In [53]:
def negative(x):
    return -x

print('max:', my_min(numbers, key=negative))
def negative_len(x):
    return -len(x)

print('Longest name:', my_min(names, key=negative_len))

max: 83
Longest name: Laurent Amstrong


In [55]:
print(numbers)
print(names)

[ 6 25 64 73 83 53 19 49 62 15]
['John Murray', 'Mike Smith', 'Sara Henderson', 'Laurent Amstrong', 'Zack Swzenks']


In [57]:
print('Min numbers:', my_min_max(numbers, lambda a, b: a < b))
print('Max numbers:', my_min_max(numbers, lambda a, b: a > b))

Min numbers: 6
Max numbers: 83


In [58]:
# Find number that has min digit
print('Number with min digit:', my_min_max(numbers, lambda a, b: a % 10 < b % 10))
# Find number that has max digit
print('Number with max digit:', my_min_max(numbers, lambda a, b: a % 10 > b % 10))
# Find longest name
print('Longest name:', my_min_max(names, lambda a, b: len(a) > len(b)))
# Find shortest name
print('Shortest name:', my_min_max(names, lambda a, b: len(a) < len(b)))
# Find name that has least vowels
print('Name with least vowels:', my_min_max(names, lambda a, b: count_vowels(a) < count_vowels(b)))
# Find name that has most vowels
print('Name with most vowels:', my_min_max(names, lambda a, b: count_vowels(a) > count_vowels(b)))
# Find name that has least consonants
print('Name with least consonants:', my_min_max(names, lambda a, b: len(a) - count_vowels(a) < len(b) - count_vowels(b)))
# Find name that has most consonants
print('Name with most consonants:', my_min_max(names, lambda a, b: len(a) - count_vowels(a) > len(b) - count_vowels(b)))

Number with min digit: 62
Number with max digit: 19
Longest name: Laurent Amstrong
Shortest name: Mike Smith
Name with least vowels: Zack Swzenks
Name with most vowels: Sara Henderson
Name with least consonants: Mike Smith
Name with most consonants: Laurent Amstrong


In [60]:
# sort name by alphabet
print(list(sorted(names)))

['John Murray', 'Laurent Amstrong', 'Mike Smith', 'Sara Henderson', 'Zack Swzenks']


In [61]:
# sort names by length
print(list(sorted(names, key=len)))

['Mike Smith', 'John Murray', 'Zack Swzenks', 'Sara Henderson', 'Laurent Amstrong']


In [76]:
# sort names by number of vowels
print(list(sorted(names, key=count_vowels)))
# sort names by number of consonants
print(list(sorted(names, key=lambda a: len(a) - count_vowels(a))))

['Zack Swzenks', 'John Murray', 'Mike Smith', 'Laurent Amstrong', 'Sara Henderson']
['Mike Smith', 'John Murray', 'Sara Henderson', 'Zack Swzenks', 'Laurent Amstrong']


In [65]:
numbers = np.random.randint(1, 100, 20)
print(numbers)
# Calculate sum of evens in numbers
# Method 1: using boolean indexing
print('Sum of evens:', sum(numbers[numbers % 2 == 0]))
# Method 2: using list comprehension
print('Sum of evens:', sum([n for n in numbers if n % 2 == 0]))

[36 49 55 90  5 77 29 18 65 21 18 16 35 25 31 16 57 42 84 94]
Sum of evens: 414
Sum of evens: 414


In [66]:
evens = list(filter(lambda a: a%2==0, numbers))
print(evens)
print(sum(evens))

[36, 90, 18, 18, 16, 16, 42, 84, 94]
414


In [67]:
print(sum(filter(lambda a: a%2==0, numbers)))

414


In [70]:
print('Even numbers:')
for i in [n for n in numbers if n%2==0]:
    print(i, end=' ')

Even numbers:
36 90 18 18 16 16 42 84 94 

In [69]:
for n in filter(lambda a: a%2==0, numbers):
    print(n, end=' ')

36 90 18 18 16 16 42 84 94 

In [71]:
numbers = np.random.randint(-99, 100, 20)
print(numbers)

[-93 -31  21   6 -39 -57  85 -74 -89   4 -71  71 -20  64  82  69  85  50
  78 -55]


In [72]:
# Count how many negative numbers
count = 0
for n in filter(lambda a: a<0, numbers):
    count += 1
print('Number of negatives:', count)

Number of negatives: 9


In [78]:
# convert negative numbers to positive
positives = list(map(lambda a: a if a>=0 else -a, numbers))
print(positives)

[93, 31, 21, 6, 39, 57, 85, 74, 89, 4, 71, 71, 20, 64, 82, 69, 85, 50, 78, 55]
